on: [push]
jobs:
  regression_testing_job:
    runs-on: ubuntu-latest
    name: a job for regression testing
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install
      - run: node ./index.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
