on: [push]
jobs:
  regression_testing_job:
    runs-on: ubuntu-latest
    name: a job for regression testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
        node-version: '12'
      - run: yarn install
      - run: node ./index.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
