on: [push]
jobs:
  regression_testing_job:
    runs-on: ubuntu-latest
    name: a job for regression testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing job step
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
